server:
  port: 8080
  servlet:
    context-path: /shop

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db
    username: root
    password: Vuzdapoet1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
